// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe1uN68vJQlpaS97Fb8lQxSnTTyybAFzE',
    appId: '1:842261795036:web:65dd99e2ca57034481a419',
    messagingSenderId: '842261795036',
    projectId: 'aplikasi-pakan-ikan',
    authDomain: 'aplikasi-pakan-ikan.firebaseapp.com',
    storageBucket: 'aplikasi-pakan-ikan.firebasestorage.app',
    measurementId: 'G-DNWGPQJW2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqCBYyEkqZuXXSYngX24UX8swQBj_G4U',
    appId: '1:842261795036:android:0c4edbce976e1e8281a419',
    messagingSenderId: '842261795036',
    projectId: 'aplikasi-pakan-ikan',
    storageBucket: 'aplikasi-pakan-ikan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjSFmLLE9712WwgqJ_zD1ZfM7iV2mHa0',
    appId: '1:842261795036:ios:90261825e0b034fa81a419',
    messagingSenderId: '842261795036',
    projectId: 'aplikasi-pakan-ikan',
    storageBucket: 'aplikasi-pakan-ikan.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjSFmLLE9712WwgqJ_zD1ZfM7iV2mHa0',
    appId: '1:842261795036:ios:90261825e0b034fa81a419',
    messagingSenderId: '842261795036',
    projectId: 'aplikasi-pakan-ikan',
    storageBucket: 'aplikasi-pakan-ikan.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe1uN68vJQlpaS97Fb8lQxSnTTyybAFzE',
    appId: '1:842261795036:web:9f576ac6a84a937b81a419',
    messagingSenderId: '842261795036',
    projectId: 'aplikasi-pakan-ikan',
    authDomain: 'aplikasi-pakan-ikan.firebaseapp.com',
    storageBucket: 'aplikasi-pakan-ikan.firebasestorage.app',
    measurementId: 'G-CTDGHF3LB8',
  );

}